inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/teaspoon_env.rb'
    - 'vendor/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 160

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
