library:
  profile_url: 'https://library.stanford.edu/staff-directory'

directory:
  org_code: JAAA
  affiliations:
    - stanford:staff
    - stanford:staff:academic
    - stanford:staff:onleave
  k5start:
    options: '-q -f /etc/keytabs/webauth.keytab -U'
    required: true
  ldapsearch:
    options:  -h directory.stanford.edu -b cn=people,dc=stanford,dc=edu
